import{a as m,S as u,i as p}from"./assets/vendor-MgecxatS.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const d=r=>m.get("https://pixabay.com/api/",{params:{key:"53333096-0ed2bac8b305690550bcf3f17",image_type:"photo",orientation:"horizontal",safesearch:!0,q:`${r}`}}).then(s=>s.data.hits),f=r=>{const{webformatURL:s,largeImageURL:i,tags:l,likes:e,views:t,comments:o,downloads:c}=r;return`<li class="gallery-item">
          <a class="img-link" href="${i}"><img class="img" src="${s}" alt="${l.split(",").slice(0,3).join(",")}"/></a>
          <ul class="img-stats-list">
            <li class="img-stats-item"><h3 class="img-stats-title">likes</h3><p class="img-stats">${e}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">views</h3><p class="img-stats">${t}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">comments</h3><p class="img-stats">${o}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">downloads</h3><p class="img-stats">${c}</p></li>
          </ul>
        </li>`},g=new u(".img-link",{captionsData:"alt",captionDelay:250}),n=r=>p.show({message:`${r}`,color:"red",position:"topRight",close:!1}),h=r=>{const s=r.map(i=>f(i)).join("");a.listEl.insertAdjacentHTML("beforeend",s),g.refresh()},y=()=>{a.listEl.innerHTML=""},b=()=>{a.listEl.insertAdjacentHTML("beforebegin",'<span class="loader"></span>')},L=()=>{document.querySelector(".loader").remove()},a={formEl:document.querySelector(".form"),inputEl:document.querySelector("input[name='search-text']"),listEl:document.querySelector(".gallery")};a.formEl.addEventListener("submit",r=>{r.preventDefault(),y();const s=a.inputEl.value.trim();if(s===""){n("Enter your query!");return}b(),d(s).then(i=>{if(L(),i.length===0){n("Sorry, there are no images matching your search query. Please try again!");return}h(i)}).catch(i=>{n(`ERROR: ${i}`)}),a.formEl.reset()});
//# sourceMappingURL=index.js.map
