import{a as m,S as u,i as d}from"./assets/vendor-MgecxatS.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const p=r=>m.get("https://pixabay.com/api/",{params:{key:"53333096-0ed2bac8b305690550bcf3f17",image_type:"photo",orientation:"horizontal",safesearch:!0,q:`${r}`}}).then(s=>s.data.hits),f=r=>{const{webformatURL:s,largeImageURL:i,tags:l,likes:e,views:t,comments:a,downloads:c}=r;return`<li class="gallery-item">
          <a class="img-link" href="${i}"><img class="img" src=${s} alt=${l}/></a>
          <ul class="img-stats-list">
            <li class="img-stats-item"><h3 class="img-stats-title">likes</h3><p class="img-stats">${e}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">views</h3><p class="img-stats">${t}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">comments</h3><p class="img-stats">${a}</p></li>
            <li class="img-stats-item"><h3 class="img-stats-title">downloads</h3><p class="img-stats">${c}</p></li>
          </ul>
        </li>`},g=new u(".img-link"),n=r=>d.show({message:`${r}`,color:"red",position:"topRight",close:!1}),h=r=>{const s=r.map(i=>f(i)).join("");o.listEl.insertAdjacentHTML("beforeend",s),g.refresh()},y=()=>{o.listEl.innerHTML=""},b=()=>{o.listEl.insertAdjacentHTML("beforebegin",'<span class="loader"></span>')},L=()=>{document.querySelector(".loader").remove()},o={formEl:document.querySelector(".form"),inputEl:document.querySelector("input[name='search-text']"),listEl:document.querySelector(".gallery")};o.formEl.addEventListener("submit",r=>{r.preventDefault(),y(),b();const s=o.inputEl.value.trim();p(s).then(i=>{if(L(),i.length===0){n("Sorry, there are no images matching your search query. Please try again!");return}h(i)}).catch(()=>{n("ERROR")}),o.formEl.reset()});
//# sourceMappingURL=index.js.map
